/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__calfews_src__canal_cy
#define __PYX_HAVE__calfews_src__canal_cy

#include "Python.h"
struct Canal_object;

/* "calfews_src/canal_cy.pxd":1
 * cdef public class Canal()[object Canal_object, type Canal_type]:             # <<<<<<<<<<<<<<
 * 
 *   cdef:
 */
struct Canal_object {
  PyObject_HEAD
  int is_Canal;
  int is_District;
  int is_Private;
  int is_Waterbank;
  int is_Reservoir;
  int locked;
  int num_sites;
  int recovery_feeder;
  PyObject *key;
  PyObject *name;
  PyObject *turnout_use;
  PyObject *flow;
  PyObject *capacity;
  PyObject *turnout;
  PyObject *flow_directions;
  PyObject *daily_turnout;
  PyObject *turnout_frac;
  PyObject *recovery_flow_frac;
  PyObject *daily_flow;
  PyObject *demand;
};

#ifndef __PYX_HAVE_API__calfews_src__canal_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) Canal_type;

#endif /* !__PYX_HAVE_API__calfews_src__canal_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcanal_cy(void);
#else
PyMODINIT_FUNC PyInit_canal_cy(void);
#endif

#endif /* !__PYX_HAVE__calfews_src__canal_cy */
