/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__calfews_src__crop_cy
#define __PYX_HAVE__calfews_src__crop_cy

#include "Python.h"
struct Crop_object;

/* "calfews_src/crop_cy.pxd":1
 * cdef public class Crop()[object Crop_object, type Crop_type]:             # <<<<<<<<<<<<<<
 * 
 *   cdef:
 */
struct Crop_object {
  PyObject_HEAD
  double sub;
  double price;
  PyObject *key;
  PyObject *water_source_list;
  PyObject *crop_list;
  PyObject *tau;
  PyObject *beta;
  PyObject *delta;
  PyObject *gamma;
  PyObject *leontief;
  PyObject *eta;
  PyObject *baseline_inputs;
  PyObject *baseline_revenue;
  PyObject *econ_factors;
  PyObject *pmp_keys;
  PyObject *crop_keys;
  PyObject *etM;
};

#ifndef __PYX_HAVE_API__calfews_src__crop_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) Crop_type;

#endif /* !__PYX_HAVE_API__calfews_src__crop_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcrop_cy(void);
#else
PyMODINIT_FUNC PyInit_crop_cy(void);
#endif

#endif /* !__PYX_HAVE__calfews_src__crop_cy */
