/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__calfews_src__delta_cy
#define __PYX_HAVE__calfews_src__delta_cy

#include "Python.h"
struct Delta_object;

/* "calfews_src/delta_cy.pxd":1
 * cdef public class Delta()[object Delta_object, type Delta_type]:             # <<<<<<<<<<<<<<
 * 
 *   cdef:
 */
struct Delta_object {
  PyObject_HEAD
  double last_year_vamp;
  double cvp_aval_stor;
  double swp_aval_stor;
  double cvp_delta_outflow_pct;
  double swp_delta_outflow_pct;
  double final_allocation_swp;
  double final_allocation_cvp;
  double rio_gains;
  double forecastSWPPUMP;
  double vernalis_gains;
  double delta_uncontrolled_remaining;
  double forecastCVPPUMP;
  double total_inflow;
  int T;
  int omr_record_start;
  int omr_rule_start;
  int vamp_rule_start;
  int first_empty_day_SWP;
  int first_empty_day_CVP;
  int iter_count;
  PyObject *model_mode;
  PyObject *key;
  PyObject *forecastSCWYT;
  PyObject *forecastSJWYT;
  PyObject *gains;
  PyObject *gains_sac;
  PyObject *gains_sj;
  PyObject *depletions;
  PyObject *vernalis_flow;
  PyObject *eastside_streams;
  PyObject *inflow;
  PyObject *ccc;
  PyObject *barkerslough;
  PyObject *dmin;
  PyObject *sodd_cvp;
  PyObject *sodd_swp;
  PyObject *TRP_pump;
  PyObject *HRO_pump;
  PyObject *outflow;
  PyObject *surplus;
  PyObject *x2;
  PyObject *eri;
  PyObject *forecastSRI;
  PyObject *forecastSJI;
  PyObject *sac_fnf;
  PyObject *hist_OMR;
  PyObject *hist_TRP_pump;
  PyObject *hist_HRO_pump;
  PyObject *fish_condition;
  PyObject *OMR;
  PyObject *swp_allocation;
  PyObject *cvp_allocation;
  PyObject *uncontrolled_swp;
  PyObject *uncontrolled_cvp;
  PyObject *annual_HRO_pump;
  PyObject *annual_TRP_pump;
  PyObject *expected_depletion;
  PyObject *remaining_outflow;
  PyObject *min_outflow;
  PyObject *export_ratio;
  PyObject *omr_reqr;
  PyObject *omr_addition;
  PyObject *rio_vista_min;
  PyObject *san_joaquin_min;
  PyObject *san_joaquin_min_flow;
  PyObject *vamp_flows;
  PyObject *new_vamp_rule;
  PyObject *san_joaquin_add;
  PyObject *san_joaquin_export_ratio;
  PyObject *d_1641_export;
  PyObject *ec_target;
  PyObject *model_params;
  PyObject *x2constraint;
  PyObject *target_allocation;
  PyObject *remaining_tax_free_storage;
  PyObject *omr_regression;
  PyObject *x2_dict;
  PyObject *max_tax_free;
  PyObject *expected_outflow;
  PyObject *pump_max;
};

#ifndef __PYX_HAVE_API__calfews_src__delta_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) Delta_type;

#endif /* !__PYX_HAVE_API__calfews_src__delta_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdelta_cy(void);
#else
PyMODINIT_FUNC PyInit_delta_cy(void);
#endif

#endif /* !__PYX_HAVE__calfews_src__delta_cy */
