/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__calfews_src__district_cy
#define __PYX_HAVE__calfews_src__district_cy

#include "Python.h"
struct District_object;

/* "calfews_src/district_cy.pxd":4
 * from .contract_cy cimport Contract
 * 
 * cdef public class District()[object District_object, type District_type]:             # <<<<<<<<<<<<<<
 * 
 *   cdef:
 */
struct District_object {
  PyObject_HEAD
  double leiu_recovery;
  double in_district_direct_recharge;
  double in_district_storage;
  double recovery_fraction;
  double surface_water_sa;
  double seepage;
  double inleiuhaircut;
  double MDD;
  double use_recharge;
  double use_recovery;
  double extra_leiu_recovery;
  double max_recovery;
  double max_leiu_exchange;
  double direct_recovery_delivery;
  double pre_flood_demand;
  double tot_leiu_recovery_use;
  double leiu_trade_cap;
  double loss_rate;
  double initial_table_a;
  double total_banked_storage;
  double min_direct_recovery;
  double turnback_sales;
  double turnback_purchases;
  double annual_private_pumping;
  double irrseasondemand;
  double recharge_rate;
  double last_days_demand_regression_error;
  double recovery_capacity_remain;
  double table_a_request;
  double current_recharge_storage;
  double current_requested;
  int is_Canal;
  int is_District;
  int is_Private;
  int is_Waterbank;
  int is_Reservoir;
  int T;
  int turnback_use;
  int must_fill;
  int seasonal_connection;
  int thismonthuse;
  int monthusecounter;
  int monthemptycounter;
  int has_private;
  int has_pesticide;
  int has_pmp;
  int k_close_wateryear;
  int iter_count;
  int contract_list_length;
  int number_years;
  int in_leiu_banking;
  PyObject *key;
  PyObject *name;
  PyObject *zone;
  PyObject *contract_list;
  PyObject *turnout_list;
  PyObject *crop_list;
  PyObject *urban_profile;
  PyObject *participant_list;
  PyObject *contract_list_all;
  PyObject *non_contract_delivery_list;
  PyObject *recharge_rate_series;
  PyObject *max_leiu_recharge;
  PyObject *max_direct_recharge;
  PyObject *delivery_location_list;
  PyObject *private_fraction;
  PyObject *recharge_decline;
  PyObject *project_contract;
  PyObject *rights;
  PyObject *service;
  PyObject *inleiucap;
  PyObject *deliveries;
  PyObject *current_balance;
  PyObject *paper_balance;
  PyObject *turnback_pool;
  PyObject *projected_supply;
  PyObject *carryover;
  PyObject *recharge_carryover;
  PyObject *delivery_carryover;
  PyObject *contract_carryover_list;
  PyObject *dynamic_recharge_cap;
  PyObject *days_to_fill;
  PyObject *daily_supplies_full;
  PyObject *recovery_use;
  PyObject *inleiubanked;
  PyObject *contract_exchange;
  PyObject *leiu_additional_supplies;
  PyObject *bank_deliveries;
  PyObject *direct_storage;
  PyObject *bank_timeseries;
  PyObject *leiu_ownership;
  PyObject *private_acreage;
  PyObject *reservoir_contract;
  PyObject *monthlydemand;
  PyObject *carryover_rights;
  PyObject *private_demand;
  PyObject *hist_demand_dict;
  PyObject *acreage_by_year;
  PyObject *private_delivery;
  PyObject *acreage;
  PyObject *annualdemand;
  PyObject *delivery_percent_coefficient;
  PyObject *pumping;
  PyObject *annual_pumping;
  PyObject *ytd_pumping;
  PyObject *demand_auto_errors;
  PyObject *demand_days;
  PyObject *dailydemand;
  PyObject *dailydemand_start;
  struct Crop_object *irrdemand;
};

#ifndef __PYX_HAVE_API__calfews_src__district_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) District_type;

#endif /* !__PYX_HAVE_API__calfews_src__district_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initdistrict_cy(void);
#else
PyMODINIT_FUNC PyInit_district_cy(void);
#endif

#endif /* !__PYX_HAVE__calfews_src__district_cy */
