/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__calfews_src__model_cy
#define __PYX_HAVE__calfews_src__model_cy

#include "Python.h"
struct Model_object;

/* "calfews_src/model_cy.pxd":10
 * 
 * 
 * cdef public class Model()[object Model_object, type Model_type]:             # <<<<<<<<<<<<<<
 * 
 *   cdef:
 */
struct Model_object {
  PyObject_HEAD
  struct __pyx_vtabstruct_11calfews_src_8model_cy_Model *__pyx_vtab;
  int T;
  int starting_year;
  int ending_year;
  int number_years;
  int T_short;
  int short_starting_year;
  int short_ending_year;
  int short_number_years;
  int sensitivity_sample_number;
  int omr_rule_start;
  int non_leap_year;
  int use_sensitivity;
  PyObject *model_mode;
  PyObject *demand_type;
  PyObject *df;
  PyObject *day_year;
  PyObject *day_month;
  PyObject *month;
  PyObject *year;
  PyObject *dowy;
  PyObject *water_year;
  PyObject *df_short;
  PyObject *short_day_year;
  PyObject *short_day_month;
  PyObject *short_month;
  PyObject *short_year;
  PyObject *short_dowy;
  PyObject *short_water_year;
  PyObject *short_days_in_month;
  PyObject *days_in_month;
  PyObject *dowy_eom;
  PyObject *leap;
  PyObject *first_d_of_month;
  PyObject *sensitivity_sample_names;
  PyObject *sensitivity_sample;
  PyObject *sensitivity_factors;
  PyObject *running_fnf;
  PyObject *reservoir_list;
  PyObject *city_list;
  PyObject *swp_allocation;
  PyObject *annual_SWP;
  PyObject *hro_pumping;
  PyObject *district_list;
  PyObject *forecastSRI;
  PyObject *contract_list;
  PyObject *waterbank_list;
  PyObject *canal_list;
  PyObject *observed_trp;
  PyObject *cvp_allocation;
  PyObject *trp_pumping;
  PyObject *observed_hro;
  PyObject *private_list;
  PyObject *annual_CVP;
  PyObject *ytd_pump_hro;
  PyObject *ytd_pump_trp;
  PyObject *observed_hro_pred;
  PyObject *urban_list;
  PyObject *leiu_list;
  PyObject *delta_gains_regression;
  PyObject *canal_reservoir;
  PyObject *canal_contract;
  PyObject *canal_priority;
  PyObject *reservoir_contract;
  PyObject *contract_turnouts;
  PyObject *contract_reservoir;
  PyObject *reservoir_canal;
  PyObject *canal_district;
  PyObject *pumping_turnback;
  PyObject *max_tax_free;
  PyObject *district_keys;
  PyObject *contract_keys;
  PyObject *allocation_losses;
  PyObject *district_keys_len;
  PyObject *canal_district_len;
  struct Reservoir_object *shasta;
  struct Reservoir_object *oroville;
  struct Reservoir_object *folsom;
  struct Reservoir_object *yuba;
  struct Reservoir_object *newmelones;
  struct Reservoir_object *donpedro;
  struct Reservoir_object *exchequer;
  struct Reservoir_object *millerton;
  struct Reservoir_object *sanluisstate;
  struct Reservoir_object *sanluisfederal;
  struct Reservoir_object *sanluis;
  struct Reservoir_object *isabella;
  struct Reservoir_object *success;
  struct Reservoir_object *kaweah;
  struct Reservoir_object *pineflat;
  struct Delta_object *delta;
  struct Canal_object *fkc;
  struct Canal_object *madera;
  struct Canal_object *xvc;
  struct Canal_object *calaqueduct;
  struct Canal_object *kwbcanal;
  struct Canal_object *aecanal;
  struct Canal_object *kerncanal;
  struct Canal_object *calloway;
  struct Canal_object *lerdo;
  struct Canal_object *beardsley;
  struct Canal_object *kernriverchannel;
  struct Canal_object *kaweahriverchannel;
  struct Canal_object *tuleriverchannel;
  struct Canal_object *kingsriverchannel;
  struct District_object *berrenda;
  struct District_object *belridge;
  struct District_object *buenavista;
  struct District_object *cawelo;
  struct District_object *henrymiller;
  struct District_object *ID4;
  struct District_object *kerndelta;
  struct District_object *losthills;
  struct District_object *rosedale;
  struct District_object *semitropic;
  struct District_object *tehachapi;
  struct District_object *tejon;
  struct District_object *westkern;
  struct District_object *wheeler;
  struct District_object *kcwa;
  struct District_object *bakersfield;
  struct District_object *northkern;
  struct District_object *arvin;
  struct District_object *delano;
  struct District_object *pixley;
  struct District_object *exeter;
  struct District_object *kerntulare;
  struct District_object *lindmore;
  struct District_object *lindsay;
  struct District_object *lowertule;
  struct District_object *porterville;
  struct District_object *saucelito;
  struct District_object *shaffer;
  struct District_object *sosanjoaquin;
  struct District_object *teapot;
  struct District_object *terra;
  struct District_object *tulare;
  struct District_object *fresno;
  struct District_object *fresnoid;
  struct District_object *socal;
  struct District_object *southbay;
  struct District_object *centralcoast;
  struct District_object *dudleyridge;
  struct District_object *tularelake;
  struct District_object *westlands;
  struct District_object *chowchilla;
  struct District_object *maderairr;
  struct District_object *othertule;
  struct District_object *otherkaweah;
  struct District_object *otherfriant;
  struct District_object *othercvp;
  struct District_object *otherexchange;
  struct District_object *othercrossvalley;
  struct District_object *otherswp;
  struct District_object *consolidated;
  struct District_object *alta;
  struct District_object *krwa;
  struct District_object *kaweahdelta;
  struct District_object *sanluiswater;
  struct District_object *panoche;
  struct District_object *delpuerto;
  struct Private_object *wonderful;
  struct Private_object *metropolitan;
  struct Private_object *castaic;
  struct Private_object *coachella;
  struct Waterbank_object *stockdale;
  struct Waterbank_object *kernriverbed;
  struct Waterbank_object *poso;
  struct Waterbank_object *pioneer;
  struct Waterbank_object *kwb;
  struct Waterbank_object *berrendawb;
  struct Waterbank_object *b2800;
  struct Waterbank_object *wkwb;
  struct Waterbank_object *irvineranch;
  struct Waterbank_object *northkernwb;
  struct Waterbank_object *aewb;
  struct Contract_object *friant1;
  struct Contract_object *friant2;
  struct Contract_object *swpdelta;
  struct Contract_object *cvpdelta;
  struct Contract_object *cvpexchange;
  struct Contract_object *crossvalley;
  struct Contract_object *kernriver;
  struct Contract_object *tuleriver;
  struct Contract_object *kaweahriver;
  struct Contract_object *kingsriver;
};

#ifndef __PYX_HAVE_API__calfews_src__model_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) Model_type;

#endif /* !__PYX_HAVE_API__calfews_src__model_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmodel_cy(void);
#else
PyMODINIT_FUNC PyInit_model_cy(void);
#endif

#endif /* !__PYX_HAVE__calfews_src__model_cy */
