/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__calfews_src__private_cy
#define __PYX_HAVE__calfews_src__private_cy

#include "Python.h"
struct Private_object;

/* "calfews_src/private_cy.pxd":4
 * from .contract_cy cimport Contract
 * 
 * cdef public class Private()[object Private_object, type Private_type]:             # <<<<<<<<<<<<<<
 * 
 *   cdef:
 */
struct Private_object {
  PyObject_HEAD
  double in_district_direct_recharge;
  double recovery_fraction;
  double use_recharge;
  double use_recovery;
  double extra_leiu_recovery;
  double max_recovery;
  double max_leiu_exchange;
  double total_banked_storage;
  double recharge_rate;
  double recovery_capacity_remain;
  double current_recharge_storage;
  double banking_risk_level;
  double total_acreage;
  int is_Canal;
  int is_District;
  int is_Private;
  int is_Waterbank;
  int is_Reservoir;
  int turnback_use;
  int thismonthuse;
  int monthusecounter;
  int monthemptycounter;
  int iter_count;
  int age_death;
  int T;
  PyObject *key;
  PyObject *name;
  PyObject *contract_list;
  PyObject *crop_list;
  PyObject *contract_list_all;
  PyObject *non_contract_delivery_list;
  PyObject *max_leiu_recharge;
  PyObject *max_direct_recharge;
  PyObject *district_list;
  PyObject *delivery_risk_rate;
  PyObject *delivery_risk;
  PyObject *target_annual_demand;
  PyObject *deliveries;
  PyObject *current_balance;
  PyObject *paper_balance;
  PyObject *turnback_pool;
  PyObject *projected_supply;
  PyObject *carryover;
  PyObject *recharge_carryover;
  PyObject *delivery_carryover;
  PyObject *contract_carryover_list;
  PyObject *dynamic_recharge_cap;
  PyObject *daily_supplies_full;
  PyObject *reservoir_contract;
  PyObject *monthlydemand;
  PyObject *carryover_rights;
  PyObject *hist_demand_dict;
  PyObject *acreage;
  PyObject *annualdemand;
  PyObject *delivery_percent_coefficient;
  PyObject *pumping;
  PyObject *annual_pumping;
  PyObject *ytd_pumping;
  PyObject *demand_auto_errors;
  PyObject *demand_days;
  PyObject *dailydemand;
  PyObject *dailydemand_start;
  PyObject *pump_out_fraction;
  PyObject *crop_maturity;
  PyObject *contract_fractions;
  PyObject *per_acre;
  PyObject *unmet_et;
  PyObject *initial_planting;
  PyObject *agedemand;
  PyObject *direct_recovery_delivery;
  PyObject *turnback_sales;
  PyObject *turnback_purchases;
  PyObject *annual_private_pumping;
  PyObject *seepage;
  PyObject *zone;
  PyObject *seasonal_connection;
  PyObject *k_close_wateryear;
  PyObject *last_days_demand_regression_error;
  PyObject *MDD;
  PyObject *has_pesticide;
  PyObject *irrdemand;
  PyObject *urban_profile;
  PyObject *contract_fraction;
  PyObject *private_fraction;
  PyObject *has_pmp;
  PyObject *turnout_list;
  PyObject *delivery_location_list;
  PyObject *must_fill;
};

#ifndef __PYX_HAVE_API__calfews_src__private_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) Private_type;

#endif /* !__PYX_HAVE_API__calfews_src__private_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initprivate_cy(void);
#else
PyMODINIT_FUNC PyInit_private_cy(void);
#endif

#endif /* !__PYX_HAVE__calfews_src__private_cy */
