/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__calfews_src__waterbank_cy
#define __PYX_HAVE__calfews_src__waterbank_cy

#include "Python.h"
struct Waterbank_object;

/* "calfews_src/waterbank_cy.pxd":1
 * cdef public class Waterbank()[object Waterbank_object, type Waterbank_type]:             # <<<<<<<<<<<<<<
 * 
 *   cdef:
 */
struct Waterbank_object {
  PyObject_HEAD
  double initial_recharge;
  double recovery;
  double tot_storage;
  double recharge_rate;
  double tot_current_storage;
  double current_requested;
  double loss_rate;
  int thismonthuse;
  int monthusecounter;
  int monthemptycounter;
  int iter_count;
  int number_years;
  int is_Canal;
  int is_District;
  int is_Private;
  int is_Waterbank;
  int is_Reservoir;
  PyObject *key;
  PyObject *name;
  PyObject *participant_list;
  PyObject *participant_type;
  PyObject *canal_rights;
  PyObject *recharge_rate_series;
  PyObject *recharge_decline;
  PyObject *ownership;
  PyObject *bank_cap;
  PyObject *storage;
  PyObject *recovery_use;
  PyObject *banked;
  PyObject *bank_timeseries;
};

#ifndef __PYX_HAVE_API__calfews_src__waterbank_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(PyTypeObject) Waterbank_type;

#endif /* !__PYX_HAVE_API__calfews_src__waterbank_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initwaterbank_cy(void);
#else
PyMODINIT_FUNC PyInit_waterbank_cy(void);
#endif

#endif /* !__PYX_HAVE__calfews_src__waterbank_cy */
