/* Generated by Cython 0.29.21 */

#ifndef __PYX_HAVE__main_cy
#define __PYX_HAVE__main_cy

#include "Python.h"

#ifndef __PYX_HAVE_API__main_cy

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C int main_cy(void);

#endif /* !__PYX_HAVE_API__main_cy */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initmain_cy(void);
#else
PyMODINIT_FUNC PyInit_main_cy(void);
#endif

#endif /* !__PYX_HAVE__main_cy */
